### ISSUE TITLE
Not working on Python 3.6

### ISSUE THREAD

**Issue by Riamse** [snoack/python-goto#7]
It seems that the part that injects NOPs into the name-lookup for 'label' isn't working:

```Python 3.6.0 (default, Dec 24 2016, 08:03:08) 
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import goto
>>> @goto.with_goto
... def dumb_increment(n):
...     """Prints integers from 0 to n inclusive"""
...     i = 0
...     label .top
...     i += 1
...     print(i)
...     if i == n:
...             goto .end
...     else:
...             goto .top
...     label .end
...     print("That's all folks")
... 
>>> dumb_increment(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in dumb_increment
NameError: name 'label' is not defined
```
It still seems to work fine on Python 2.7:
```Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import goto
>>> @goto.with_goto
... def dumb_increment(n):
...     """See above"""
...     i = 0
...     label .top
...     i += 1
...     print(i)
...     if i == n:
...             goto .end
...     else:
...             goto .top
...     label .end
...     print("That's all folks")
... 
>>> dumb_increment(3)
1
2
3
That's all folks
```

**Comment by Riamse** [comment]
It also seems that the part that replaces the opcodes for the goto part doesn't work either:
```>>> @goto.with_goto
... def hello():
...     import random
...     label .thelabel
...     if 123 in f"{random.random()}":
...             return 'hello!'
...     else:
...             goto .thelabel
... 
>>> import dis
>>> dis.dis(hello)
  3           0 LOAD_CONST               1 (0)
              2 LOAD_CONST               0 (None)
              4 IMPORT_NAME              0 (random)
              6 STORE_FAST               0 (random)

  4           8 LOAD_GLOBAL              1 (label)
             10 LOAD_ATTR                2 (thelabel)
             12 POP_TOP

  5          14 LOAD_CONST               2 (123)
             16 LOAD_FAST                0 (random)
             18 LOAD_ATTR                0 (random)
             20 CALL_FUNCTION            0
             22 FORMAT_VALUE             0
             24 COMPARE_OP               6 (in)
             26 POP_JUMP_IF_FALSE       32

  6          28 LOAD_CONST               3 ('hello!')
             30 RETURN_VALUE

  8     >>   32 LOAD_GLOBAL              3 (goto)
             34 LOAD_ATTR                2 (thelabel)
             36 POP_TOP
             38 LOAD_CONST               0 (None)
             40 RETURN_VALUE
```

**Comment by snoack** [comment]
In fact, on Python 3.6, the `goto()` decorator didn't do anything to the bytecode, as even `_find_labels_and_gotos()` failed to find anything. The reason therefore was [a change to the bytecode format in Python 3.6](https://bugs.python.org/issue26647). This has been fixed now.
